Serialise origin bucket modifications
cloudposse/terraform-aws-cloudfront-s3-cdn pull request #136
Opened 2021-03-08 02:33 UTC by alexjurkiewicz

You can't modify an S3 bucket's policy & public access block at the same
time, AWS API will complain:

OperationAborted: A conflicting conditional operation is currently in progress against this resource

Serialise operations to the origin bucket so we don't run into this
error. The suggested fix is from

https://github.com/hashicorp/terraform-provider-aws/issues/7628

2021-03-09 09:35 UTC, joe-niland commented
/test all

2021-03-09 21:45 UTC, joe-niland commented on main.tf
> +  bucket = aws_s3_bucket.origin.bucket
```suggestion
  bucket = join("", aws_s3_bucket.origin.*.bucket)
```

2021-03-09 21:46 UTC, joe-niland requested changes
@alexjurkiewicz just a small typo to fix

2021-03-10 02:03 UTC, alexjurkiewicz commented
Thank you! Fixed

On Wed, 10 Mar 2021 at 08:47, Joe Niland <notifications@github.com> wrote:

> *@joe-niland* requested changes on this pull request.
>
> @alexjurkiewicz <https://github.com/alexjurkiewicz> just a small typo to
> fix
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/136#pullrequestreview-608112415>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAC4U5LLPQY6GUM5KOFCEVTTC2JOBANCNFSM4YYRRGNA>
> .
>

2021-03-10 02:32 UTC, joe-niland commented
/test bats

2021-03-10 02:38 UTC, joe-niland commented
/test readme

2021-03-10 02:56 UTC, joe-niland approved these changes

2021-03-10 02:56 UTC, merged

2021-03-10 02:56 UTC, joe-niland commented
Thank you @alexjurkiewicz !