Fix: Deployment Principal ARNs
cloudposse/terraform-aws-cloudfront-s3-cdn pull request #164
Opened 2021-05-14 22:26 UTC by korenyoni

## what
* Add test for `deployment_principal_arns`
* Fix order of nested functions when rendering bucket policy for `deployment_principal_arns` — otherwise an error occurs when comparing types.
* Fix snippet: all prefixes must begin in forward slash or otherwise the bucket policy JSON will be invalid.
* Fix snippet passing incorrect variable name.

### (misc)
* Fix typo in tfvars fixtures in example.
* Add enablement toggles to all resources in example
* Fix minimum_protocol_version being passed when it won't be honored by AWS i.e. when s3_access_log_bucket_name is true as a result of acm_certificate_arn being unset.
* Fix default for s3_access_log_bucket_name — it is supposed to be empty and there is a check for its length in locals{} that assumes it is empty by default, but it is not empty by default.

## why
* `deployment_principal_arns` was not working and `examples/complete` was not testing for it

## references
* #160

2021-05-14 22:35 UTC, korenyoni commented
/test all

2021-05-14 22:49 UTC, jamengual approved these changes

2021-05-14 22:52 UTC, Nuru requested changes

2021-05-14 22:52 UTC, Nuru commented on examples/complete/fixtures.us-east-2.tfvars
> +parent_zone_name = "testing.cloudposse.com"
Testing domain is `.co` _[sic]_
```suggestion
parent_zone_name = "testing.cloudposse.co"

```

2021-05-14 22:52 UTC, Nuru commented on examples/complete/main.tf
> +        Sid       = ""
```suggestion
        Sid       = "EnableTestRole${each.key}"
```

2021-05-14 22:52 UTC, Nuru commented on main.tf
> +    minimum_protocol_version       = var.acm_certificate_arn == "" ? "TLSv1" : var.minimum_protocol_version # If cloudfront_default_certificate=true, only TLSv1 can be specified (see: https://docs.aw
This should be documented in the `minimum_protocol_version` variable description, not fixed here. Fixing it here leaves users having set `minimum_protocol_version ="TLSv1.2"` thinking they have it set but secretly not.

2021-05-16 13:59 UTC, korenyoni commented
/test all

2021-05-16 14:26 UTC, korenyoni commented
Tests are currently stuck in queued due to a GitHub Actions incident

2021-05-16 19:38 UTC, korenyoni commented
/test all

2021-05-16 19:47 UTC, korenyoni commented
Will need to remove validation due to Terraform version used in tests being too old for functions used in validation block.

2021-05-16 20:05 UTC, korenyoni commented
/test all

2021-05-16 20:49 UTC, korenyoni commented
/test all

2021-05-16 20:57 UTC, korenyoni commented
/test all

2021-05-16 22:22 UTC, korenyoni commented
/test all

2021-05-17 02:50 UTC, Nuru commented
/test all

2021-05-17 02:50 UTC, Nuru submitted a review, later dismissed

2021-05-17 12:15 UTC, korenyoni commented
@Nuru thank you — yes it does seem better to programatically handle the leading slash and not have the user deal with it. I just fixed a couple of typos in `deployment.tf`

2021-05-17 12:16 UTC, korenyoni commented
/test all

2021-05-17 12:30 UTC, korenyoni commented on main.tf
> +      formatlist("${local.origin_bucket.arn}/%s*", each.value),
This is a better way of ensuring the bucket policy is valid, as we're handling the slash programatically now instead of deferring it to the user.

2021-05-17 13:12 UTC, aknysh approved these changes

2021-05-17 13:17 UTC, merged

2021-05-17 14:18 UTC, mcalhoun reviewed
LGTM!