Add external_aliases which get no cnames created for them
cloudposse/terraform-aws-cloudfront-s3-cdn pull request #199
Opened 2021-12-01 23:59 UTC by mburns

## what
* allow for aliases in Cloudfront which do not get the corresponding CNAME record created in Route53

## why
* Not all Cloudfront'd domains are managed in Route53
* This is similar to `dns_alias_enabled`, but allows for a mixture of DNS providers for a single Cloudfront Distribution

2021-12-13 15:57 UTC, korenyoni commented
@mburns are you able to please add BridgeCrew exceptions for the failing checks outlined in this PR?

2021-12-13 16:00 UTC, korenyoni requested changes
LGTM. But please see comments regarding BridgeCrew.

2021-12-13 16:00 UTC, korenyoni commented on main.tf
> +    for_each = distinct(compact(concat(var.cors_allowed_origins, var.aliases, var.external_aliases)))
Please add BridgeCrew exceptions for these errors

2021-12-13 16:00 UTC, korenyoni commented on main.tf
> +  aliases = var.acm_certificate_arn != "" ? concat(var.aliases, var.external_aliases) : []
Same here — please add a BridgeCrew exception

2021-12-13 22:48 UTC, korenyoni commented
Hey @mburns — I see that you reverted the BridgeCrew exceptions, was there a particular reason why?

2021-12-13 22:50 UTC, mburns commented
HI @korenyoni, just troubleshooting, sorry. It looked like the errors were fixed with merging the latest master.

2021-12-13 22:52 UTC, korenyoni commented
/test all

2021-12-13 22:58 UTC, korenyoni commented
@mburns I'm honestly not sure why the BridgeCrew check is still failing — I will have to take a closer look tomorrow.

<img width="871" alt="CleanShot 2021-12-14 at 00 57 21@2x" src="https://user-images.githubusercontent.com/10080107/145902353-71edea53-c5bb-45bf-b5e0-e1f04be4faac.png">

2021-12-14 10:15 UTC, korenyoni commented
/test all

2021-12-14 10:38 UTC, korenyoni commented
<img width="949" alt="CleanShot 2021-12-14 at 12 35 31@2x" src="https://user-images.githubusercontent.com/10080107/145982110-b1ef48e7-736a-4861-b9d9-51d93b0cf0be.png">

I'm still not sure why BC is failing in the GitHub checks API.

Originally, it was because `examples/complete`'s module instantiation was showing up in BridgeCrew without the suppressions: 
<img width="1397" alt="CleanShot 2021-12-14 at 12 09 38@2x" src="https://user-images.githubusercontent.com/10080107/145982289-98d4ce4a-5f0c-496a-a7f2-f925196ad9c1.png">

I'm not sure why it's still happening though. As you can see, it's passing in BC itself.

<img width="1450" alt="CleanShot 2021-12-14 at 12 35 47@2x" src="https://user-images.githubusercontent.com/10080107/145982172-2ccf90fb-b131-4766-ab42-bf215c8614ee.png">

@mburns I've also taken over your PR and just expanded the suppression comments and moved the suppressions to the top of the resource definition blocks.

Anyways, I'm going to merge this in and hope the BC errors do not keep happening in subsequent PRs.

2021-12-14 10:40 UTC, korenyoni approved these changes

2021-12-14 10:41 UTC, merged